channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy ==1.24.1
  - pip >=22.3.1
  - matplotlib >=3.6.3
  - pandas >=1.5.3
  - scipy >=1.9.0
  - scikit-learn >=1.2.1
  - loguru >=0.6.0
