channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.11
  - numpy ==1.24.3
  - pip >=22.3.1
  - matplotlib >=3.6.3
  - pandas >=2.0.2
  - scipy >=1.9.0
  - scikit-learn >=1.2.1
  - loguru >=0.6.0
  - pytest >=7.2.15
  - pytest-cov >=4.0.0
