channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy >=1.25.2
  - pip >=23.2.1
  - matplotlib >=3.8.0
  - pandas >=2.1.0
  - scipy >=1.11.4
  - scikit-learn >=1.3.2
  - loguru >=0.7.2
  - pytest >=7.4.2
  - pytest-cov >=4.1.0
