channels:
  - conda-forge
dependencies:
  - numpy >=2.0.1
  - pip >=23.2.1
  - matplotlib >=3.9.0
  - pandas >=2.1.0
  - scipy >=1.14.0
  - scikit-learn >=1.5.1
  - loguru >=0.7.2
  - pytest >=7.4.2
  - pytest-cov >=4.1.0
