channels:
  - conda-forge
dependencies:
  - python >=3.7.1,<3.10
  - pip >=21.3.1
  - matplotlib >=3.4.2,<3.6.0
  - pandas >=1.3.2,<1.4.3
  - scipy >=1.8.1
  - scikit-learn >=0.24.2,<1.1.2
  - pip:
      - loguru >=0.5.3
      - pytest >=6.2.5
      - pytest-cov >=2.12.1
