name: Branch Name Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  branch-name-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Name
        run: |
          # Define your branch name pattern using regex
          modules="distributions|tools|sensitivity|plot|parameters|metrics|eva|confidence_interval|dev"

          pattern=f"^({modules})/(feature|bugfix|hotfix|release|docs)(/[a-zA-Z0-9_-]+)?$"

          branch_name=$(echo "${{ github.ref }}" | awk -F/ '{print $3}')

          if [[ ! "${branch_name}" =~ ${pattern} ]]; then
            echo "Branch name does not match the naming convention."
            echo "Expected format: 'type/branch-name'"
            exit 1
          fi

        shell: bash
