name: Branch Name Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  branch-name-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: get_branch
        run: |
          # Extract the branch name from the ref
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          elif [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            BRANCH_NAME=$(echo "${GITHUB_REF}" | cut -d'/' -f3)
          fi
          echo "Branch name is ${BRANCH_NAME}"
          echo "::set-output name=branch::${BRANCH_NAME}"
      - name: Check Branch Name
        run: |
          # Define your branch name pattern using regex
          modules="distributions|tools|sensitivity|plot|parameters|metrics|eva|confidence_interval|dev"
          pattern="^({modules})/(feature|bugfix|hotfix|release|docs)(/[a-zA-Z0-9_-]+)?$"
          # branch_name=$(echo "${{ github.ref }}" | awk -F/ '{print $3}')
          # Get the branch name from the previous step output
          BRANCH_NAME="${{ steps.get_branch.outputs.branch }}"
          if [[ ! "${branch_name}" =~ ${pattern} ]]; then
            echo "Branch name does not match the naming convention."
            echo "Expected format: '${pattern}'"
            echo "given: '${branch_name}'"
            exit 1
          fi

        shell: bash
